apiVersion: v2
name: same3na-bootstrap-chart
description: Installs the bootstrap component required for the cluster
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx