apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-secret-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.17.0
    releaseName: external-secrets
    valuesFile: values.yaml
