apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - ingress.yaml

helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: 2.10.2
    releaseName: loki-stack
    valuesFile: values.yaml
