{{ $initialScope := . }}
{{- range $i, $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}
  namespace: {{ $initialScope.Values.namespace }}
  {{- with $config.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- with $config.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

