{{ $initialScope := . }}
{{- range $i, $depl := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $depl.name }}
  namespace: {{ $initialScope.Values.namespace }}
  {{- with $depl.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  replicas: {{ $depl.replicas }}
  selector:
    matchLabels:
      app: {{ $depl.name }}
  template:
    metadata:
      labels:
        app: {{ $depl.name }}
    spec:
      {{- with $depl.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $depl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $depl.containers }}
      containers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $depl.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
