{{ $initialScope := . }}
{{- range $i, $secret := .Values.external_secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $initialScope.Values.namespace }}
spec:
  refreshInterval: 1h
  {{- with $secret.secretStoreRef}}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end}}

  {{- with $secret.target}}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end}}

  {{- with $secret.data}}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end }}

