{{ $initialScope := . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: {{ $initialScope.Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt  # If using SSL
spec:
  ingressClassName: nginx
  rules:
  - host: same3na.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000  # Your internal service port

  - host: api-staging.same3na.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-app-staging
            port:
              number: 8800  # Your internal service port

  - host: staging.same3na.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-staging
            port:
              number: 3300  # Your internal service port
              