{{ $initialScope := . }}
{{- range $i, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $initialScope.Values.namespace }}
  {{- with $secret.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
type: Opaque
{{- with $secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

