apiVersion: v2
name: my-cert-manager
description: A Helm chart to install cert-manager
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: v1.17.2
    repository: https://charts.jetstack.io