---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/same3na/helm.git
      name: same3na-helm
      type: git
      usernameSecret:
        name: argo-secrets
        key: GITHUB_USERNAME
      passwordSecret:
        name: argo-secrets
        key: GITHUB_TOKEN