---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore

  target:
    name: argo-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_USERNAME
      remoteRef:
        key: secret/same3na/config
        property: GITHUB_USERNAME

    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: secret/same3na/config
        property: GITHUB_TOKEN
