apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
  - same3na-app-prod-application.yaml
  - ingress.yaml
  - external-secrets.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yaml